"""
Telegram Bot - Sends formatted daily digest
"""

import asyncio
import httpx
from typing import Dict
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

URGENCY_EMOJI = {"high": "🔥", "medium": "📊", "low": "💡"}
CATEGORY_EMOJI = {
    "japan": "🇯🇵", "global": "🌐", "us": "🇺🇸", "china": "🇨🇳",
    "geopolitics": "⚔️", "markets": "📈",
    # legacy
    "macro": "🌐", "micro": "🏢",
}


class TelegramBot:
    def __init__(self, token: str, chat_id: str):
        self.token = token
        self.chat_id = chat_id
        self.base_url = f"https://api.telegram.org/bot{token}"

    async def send_digest(self, digest: Dict):
        messages = self._format_digest(digest)
        async with httpx.AsyncClient(timeout=30) as client:
            for i, msg in enumerate(messages):
                resp = await client.post(
                    f"{self.base_url}/sendMessage",
                    json={
                        "chat_id": self.chat_id,
                        "text": msg,
                        "parse_mode": "HTML",
                        "disable_web_page_preview": True,
                    },
                )
                if resp.status_code != 200:
                    logger.error(f"Telegram message {i+1} failed: {resp.text}")
                if i < len(messages) - 1:
                    await asyncio.sleep(1)  # avoid Telegram 429 rate-limit (1 msg/sec per chat)

    def _format_digest(self, digest: Dict) -> list[str]:
        messages = []
        today = datetime.now().strftime("%Y年%m月%d日")

        # ===== Message 1: Header + Overview =====
        header = f"""🗾 <b>Japan Finance Daily Digest</b>
📅 {today}
{'─' * 30}

🌐 <b>Vĩ mô hôm nay:</b>
{digest.get('macro_summary', '—')}

🏢 <b>Vi mô / Doanh nghiệp:</b>
{digest.get('micro_summary', '—')}"""

        if digest.get("weekly_theme"):
            header += f"\n\n📌 <b>Chủ đề tuần này:</b> {digest['weekly_theme']}"

        if digest.get("alert"):
            header += f"\n\n⚠️ <b>Cảnh báo:</b> {digest['alert']}"

        messages.append(header)

        # ===== Message 2+: Top Topics =====
        topics = digest.get("top_topics", [])
        if not topics:
            messages.append("❌ Không có topic nào được tìm thấy hôm nay.")
            return messages

        topics_msg = f"🎯 <b>本日のホットトピック Top 2</b>\n{'─' * 30}\n\n"

        for topic in topics[:2]:
            urgency = topic.get("urgency", "medium")
            category = topic.get("category", "macro")
            emoji = URGENCY_EMOJI.get(urgency, "📊")
            cat_emoji = CATEGORY_EMOJI.get(category, "📊")

            flag = topic.get("country_flag", "")
            topics_msg += f"""{emoji} <b>#{topic['rank']} {flag} — {topic['title']}</b>
{cat_emoji} {category.upper()} | 緊急度: <b>{urgency.upper()}</b>

💬 <b>なぜ今重要か:</b>
{topic.get('why_trending', '—')}
🎬 {topic.get('video_angle', '—')}

✍️ <b>推奨タイトル:</b>
<code>{topic.get('suggested_title', '—')}</code>

📝 <b>Key points:</b>"""

            for point in topic.get("key_points", [])[:3]:
                topics_msg += f"\n  • {point}"

            if topic.get("japan_connection"):
                topics_msg += f"\n\n🇯🇵 <b>日本への影響:</b> {topic['japan_connection']}"

            if topic.get("thumbnail_number"):
                topics_msg += f"\n📸 <b>Thumbnail数字:</b> <code>{topic['thumbnail_number']}</code>"

            if topic.get("shorts_hooks") and topic.get("rank") == 1:
                topics_msg += f"\n\n📱 <b>Shorts ideas (60秒):</b>"
                for hook in topic["shorts_hooks"][:3]:
                    topics_msg += f"\n  ▶ {hook}"

            topics_msg += f"\n\n{'─' * 25}\n\n"

            # Split into multiple messages if too long
            if len(topics_msg) > 3500:
                messages.append(topics_msg)
                topics_msg = ""

        if topics_msg:
            messages.append(topics_msg)

        # ===== Footer =====
        messages.append(
            f"🤖 <i>Generated by Japan Finance AI Agent</i>\n"
            f"⏰ {datetime.now().strftime('%H:%M')} JST\n\n"
            f"🔗 Channel: @shiba_japan_finance"
        )

        return messages
