"""
Telegram Bot - Sends formatted daily digest
"""

import asyncio
import httpx
from typing import Dict
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

URGENCY_EMOJI = {"high": "🔥", "medium": "📊", "low": "💡"}
CATEGORY_EMOJI = {"macro": "🌐", "micro": "🏢"}


class TelegramBot:
    def __init__(self, token: str, chat_id: str):
        self.token = token
        self.chat_id = chat_id
        self.base_url = f"https://api.telegram.org/bot{token}"

    async def send_digest(self, digest: Dict):
        messages = self._format_digest(digest)
        async with httpx.AsyncClient(timeout=30) as client:
            for i, msg in enumerate(messages):
                resp = await client.post(
                    f"{self.base_url}/sendMessage",
                    json={
                        "chat_id": self.chat_id,
                        "text": msg,
                        "parse_mode": "HTML",
                        "disable_web_page_preview": True,
                    },
                )
                if resp.status_code != 200:
                    logger.error(f"Telegram message {i+1} failed: {resp.text}")
                if i < len(messages) - 1:
                    await asyncio.sleep(1)  # avoid Telegram 429 rate-limit (1 msg/sec per chat)

    def _format_digest(self, digest: Dict) -> list[str]:
        messages = []
        today = datetime.now().strftime("%Y年%m月%d日")

        # ===== Message 1: Header + Overview =====
        header = f"""🗾 <b>Japan Finance Daily Digest</b>
📅 {today}
{'─' * 30}

🌐 <b>Vĩ mô hôm nay:</b>
{digest.get('macro_summary', '—')}

🏢 <b>Vi mô / Doanh nghiệp:</b>
{digest.get('micro_summary', '—')}"""

        if digest.get("weekly_theme"):
            header += f"\n\n📌 <b>Chủ đề tuần này:</b> {digest['weekly_theme']}"

        if digest.get("alert"):
            header += f"\n\n⚠️ <b>Cảnh báo:</b> {digest['alert']}"

        messages.append(header)

        # ===== Message 2+: Top Topics =====
        topics = digest.get("top_topics", [])
        if not topics:
            messages.append("❌ Không có topic nào được tìm thấy hôm nay.")
            return messages

        topics_msg = f"🎯 <b>Top Topics để làm video hôm nay</b>\n{'─' * 30}\n\n"

        for topic in topics[:5]:
            urgency = topic.get("urgency", "medium")
            category = topic.get("category", "macro")
            emoji = URGENCY_EMOJI.get(urgency, "📊")
            cat_emoji = CATEGORY_EMOJI.get(category, "📊")

            topics_msg += f"""{emoji} <b>#{topic['rank']} — {topic['title']}</b>
{cat_emoji} {category.upper()} | Độ hot: <b>{urgency.upper()}</b>
🇯🇵 <i>{topic.get('title_jp', '')}</i>
📖 {topic.get('explanation_vi', '—')}

💬 <b>Phân tích & góc video:</b>
{topic.get('why_trending', '—')}
🎬 {topic.get('video_angle', '—')}

✍️ <b>Gợi ý tiêu đề:</b>
<code>{topic.get('suggested_title', '—')}</code>

📝 <b>Key points:</b>"""

            for point in topic.get("key_points", [])[:3]:
                topics_msg += f"\n  • {point}"

            topics_msg += f"\n\n{'─' * 25}\n\n"

            # Split into multiple messages if too long
            if len(topics_msg) > 3500:
                messages.append(topics_msg)
                topics_msg = ""

        if topics_msg:
            messages.append(topics_msg)

        # ===== Footer =====
        messages.append(
            f"🤖 <i>Generated by Japan Finance AI Agent</i>\n"
            f"⏰ {datetime.now().strftime('%H:%M')} JST\n\n"
            f"🔗 Channel: @shiba_japan_finance"
        )

        return messages
